### ISSUE TITLE
博客评论不了

### ISSUE THREAD

**Issue by yqlizeao** [hxhb/blog-comments#124]
博客评论不了，好麻烦啊，接个LiveRe吧

**Comment by hxhb** [comment]
登录了github就可以评论啊。

**Comment by yqlizeao** [comment]
![image](https://user-images.githubusercontent.com/16096037/81544253-d7f2ef80-93a9-11ea-9b07-d7c3229e4536.png)

**Comment by hxhb** [comment]
额，用的评论系统升级了，最新的两篇文章没有初始化，现在可以了。

**Comment by yqlizeao** [comment]
已评论。带佬就是不一样！
